[plugin]
prepend_previewers = [
  { url = "*.md", run = "mermaid" },
  { url = "*.markdown", run = "mermaid" },
  { url = "*.mmd", run = "mermaid" },
  { url = "*.mermaid", run = "mermaid" },
  { url = "*.txt", run = "mdv-previewer" },
]

prepend_preloaders = [
  { url = "*.txt", run = "mdv-previewer" },
]
